### PR TITLE
Feature: align query sequence to a given reference

### PR DESCRIPTION
**Pull request by xileF1337**
As discussed in #4, this adds a method `align` to the `Bio::Cigar` class that aligns a query sequence to a reference sequence using the stored CIGAR string representation. It has built-in support for reverse-complemented sequences and the reference/start position value as found in SAM files. 

I also added a test suite `2-align.t`. I renamed the existing `basic.t` test file to `1-basic.t` to ensure the tests are run in the proper order. I added a single new dependency, `Test::Exception`, to ensure my sanity checks work properly. I hope this is okay for you; it's a quite lightweight module. 

Finally, I added this minimal example to the synopsis:
```perl
my $query = "GCAAATGC";                                                    
my $ref   = "AAAAGCAAATGC";                                                
my $aln   = $cigar->align($query, $ref, 5);  # align query to pos 5 of ref 
say foreach @$aln;
```

### CODE REVIEW

**Comment by xileF1337** [comment]
@tsibley any thoughts?

**Comment by tsibley** [comment]
@xileF1337 Thanks for this! I was out on vacation last week and catching back up on work this week. Initial impression on a cursory glance is that this looks good. I'll try to take a closer look with comments sooner than later.

**Comment by xileF1337** [comment]
I have tried and tested the implementation for a while now and it seems to work quite well.

**Comment by xileF1337** [comment]
Bump @tsibley, have you looked at my PR already? It would be awesome to have this stuff on CPAN :sunglasses:  If I can help any further with anything, please let me know!

**Comment by xileF1337** [comment]
@tsibley Have you had a look at this yet?

**Comment by tsibley** [comment]
@xileF1337 I've reworked this PR as https://github.com/tsibley/Bio-Cigar/compare/3267717...a36d34b over on my fork. Will cut a new CPAN release from there.

Thank you again for this contribution!

**Comment by tsibley** [comment]
Released as 1.02. Already on CPAN mirrors and should be indexed by PAUSE soon.

**Comment by xileF1337** [comment]
Awesome, I'll give the new release a test in the coming week. Thanks for merging this!

**Pull request closed without merging**
